name: homemenu
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  # assets:


  #----------------Local Assets-----------------#
  assets:
    - assets/1kg_chicken.png
    - assets/boiling_sauce.jpg
    - assets/chicken.jpg
    - assets/chota_masala.jpg
    - assets/cooking_rice.jpg
    - assets/water_boil.png
    - assets/two_wistles.jpg
    - assets/soked_rice.png
    - assets/secreat_sauce.jpg
    - assets/oil_ghee.jpg
    - assets/marination.jpg
    - assets/main_marination.jpg
    - assets/mahfil_biryani.jpg
    - assets/layring.jpg
    - assets/frying_onion.jpg
    - assets/fined_sauce.jpg
    - assets/dum.jpg
    - assets/done.jpg
    - assets/cooking.jpg



 